"""
Generates a runnable FastMCP server scaffold from the endpoints that
passed the AI-readiness audit. Each OpenAPI operation becomes an MCP
tool with a model-facing description (distinct from the raw API docs).
"""

import re


def _to_snake_case(path: str, method: str) -> str:
    name = re.sub(r"[{}]", "", path)
    name = re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower()
    return f"{method.lower()}_{name}"


def _to_python_identifier(name: str) -> str:
    """Sanitize an OpenAPI parameter name (e.g. 'Idempotency-Key') into a valid Python identifier."""
    ident = re.sub(r"[^a-zA-Z0-9_]", "_", name).lower()
    if ident and ident[0].isdigit():
        ident = f"_{ident}"
    return ident or "param"


def _model_facing_description(ep) -> str:
    """
    Rewrites the raw OpenAPI description into something aimed at a model's
    tool-selection decision: what it's for, and when to use it vs. not.
    """
    base = ep.description.strip() or ep.summary.strip() or f"{ep.method.upper()} {ep.path}"
    write_methods = {"post", "put", "patch", "delete"}
    if ep.method.lower() in write_methods:
        note = " NOTE: this endpoint has side effects — it changes data, it is not read-only."
    else:
        note = " This is a read-only lookup — safe to call speculatively."
    return base + note


def _request_body_fields(ep) -> list:
    """
    Extract request-body properties as callable arguments.

    Without this, a POST endpoint's real payload fields are silently dropped and
    the generated tool is uncallable — the model can invoke it but has no way to
    say what to create.

    Returns a list of (original_name, identifier, is_required) tuples.
    """
    body = ep.request_body if isinstance(ep.request_body, dict) else {}
    content = body.get("content") or {}
    schema = {}
    for media_type, media in content.items():
        if "json" in str(media_type).lower() and isinstance(media, dict):
            candidate = media.get("schema")
            if isinstance(candidate, dict):
                schema = candidate
                break

    props = schema.get("properties") or {}
    required = set(schema.get("required") or [])
    return [
        (name, _to_python_identifier(name), name in required)
        for name in props
    ]


def _server_slug(title: str) -> str:
    """
    Turn an API title into a short, stable server identifier.

    Used both for the MCP server name and for the suggested client config key,
    so a generated server identifies itself as (say) "spotify-web-api" rather
    than the generic placeholder every generated server used to share.
    """
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", title).strip("-").lower()
    return slug or "generated-api"


def _tool_annotations(ep) -> str:
    """
    Build a ToolAnnotations literal for this endpoint.

    MCP has first-class, machine-readable hints for exactly what category 2
    cares about. Prose in the description helps a model reason; annotations let
    a *client* enforce — e.g. auto-approving read-only calls while requiring
    confirmation for destructive ones. Emitting both is strictly better than
    prose alone.

    camelCase is used deliberately: mcp 1.x defines these fields in camelCase
    and 2.x defines them in snake_case, but both accept camelCase, so it's the
    spelling that works across versions.
    """
    method = ep.method.lower()
    read_only = method in {"get", "head", "options"}

    hints = [f"readOnlyHint={read_only}"]
    if not read_only:
        # DELETE and PUT replace or remove state; POST/PATCH usually add or amend.
        hints.append(f"destructiveHint={method in {'delete', 'put'}}")
        # PUT and DELETE are idempotent by HTTP semantics; POST and PATCH are not.
        hints.append(f"idempotentHint={method in {'put', 'delete'}}")
    # The endpoint reaches an external system, so the world is not closed.
    hints.append("openWorldHint=True")
    return "ToolAnnotations(" + ", ".join(hints) + ")"


def generate_mcp_scaffold(spec: dict, endpoints: list, out_path: str):
    base_url = ""
    servers = spec.get("servers", [])
    if servers:
        base_url = servers[0].get("url", "")

    info = spec.get("info") or {}
    api_title = str(info.get("title", "Unknown API"))
    api_version = str(info.get("version", "unknown"))

    lines = []
    lines.append('"""')
    lines.append(f"MCP server scaffold for {api_title} (v{api_version}).")
    lines.append("")
    lines.append("Auto-generated by agent-ready from an OpenAPI spec:")
    lines.append("    https://github.com/sfaisal/agent-ready")
    lines.append("")
    lines.append("REQUIREMENTS")
    lines.append("    pip install mcp httpx")
    lines.append("")
    lines.append("    Works with both SDK generations — mcp 1.x (FastMCP) and 2.x")
    lines.append("    (MCPServer). See the import shim below.")
    lines.append("")
    lines.append("RUN")
    lines.append("    python " + out_path.split("/")[-1])
    lines.append("")
    lines.append("    Or register it with an MCP client. For Claude Desktop, add to")
    lines.append("    claude_desktop_config.json:")
    lines.append("")
    lines.append('        {"mcpServers": {"' + _server_slug(api_title) + '": {')
    lines.append('            "command": "python",')
    lines.append('            "args": ["/absolute/path/to/' + out_path.split("/")[-1] + '"]}}}')
    lines.append("")
    lines.append("BEFORE YOU SHIP THIS")
    lines.append("    1. Review every tool description. These are a first draft, rewritten")
    lines.append("       to be model-facing rather than copied from the API docs — but a")
    lines.append("       generator cannot tell whether a description is actually accurate.")
    lines.append("    2. Add authentication. This scaffold sends no credentials, so calls")
    lines.append("       against a real API will fail with 401/403 until you wire in a")
    lines.append("       token or key.")
    lines.append("    3. Consider whether every tool here should be exposed. Fewer, tighter")
    lines.append("       tools generally beat more, richer ones.")
    lines.append('"""')
    lines.append("")
    lines.append("import httpx")
    lines.append("from mcp.types import ToolAnnotations")
    lines.append("")
    lines.append("# The server class moved in mcp 2.0: FastMCP was replaced by MCPServer.")
    lines.append("# The decorator and run() APIs are otherwise compatible, so support both.")
    lines.append("try:")
    lines.append("    from mcp.server import MCPServer as _Server  # mcp >= 2.0")
    lines.append("except ImportError:  # pragma: no cover - depends on installed SDK")
    lines.append("    from mcp.server.fastmcp import FastMCP as _Server  # mcp 1.x")
    lines.append("")
    lines.append(f'BASE_URL = "{base_url}"')
    lines.append("")
    lines.append(f'mcp = _Server("{_server_slug(api_title)}")')
    lines.append("")

    for ep in endpoints:
        func_name = _to_snake_case(ep.path, ep.method)
        description = _model_facing_description(ep)
        params = [p for p in ep.parameters if isinstance(p, dict) and p.get("name")]

        path_params, query_params, header_params = [], [], []
        for p in params:
            location = p.get("in", "query")
            entry = (p["name"], _to_python_identifier(p["name"]), bool(p.get("required")))
            if location == "path":
                # Path parameters are always required — the URL is malformed without them.
                path_params.append((entry[0], entry[1], True))
            elif location == "header":
                header_params.append(entry)
            else:
                query_params.append(entry)

        body_fields = _request_body_fields(ep)

        # Required arguments must come first and carry no default, which is how
        # the SDK derives the `required` array in the advertised inputSchema.
        all_args = path_params + query_params + header_params + body_fields
        required_args = [a for a in all_args if a[2]]
        optional_args = [a for a in all_args if not a[2]]

        sig_parts = [f"{ident}: str" for _, ident, _ in required_args]
        sig_parts += [f"{ident}: str = None" for _, ident, _ in optional_args]
        sig_params = ", ".join(sig_parts)

        url_path = ep.path
        for original, ident, _ in path_params:
            url_path = url_path.replace("{" + original + "}", "{" + ident + "}")

        lines.append(f"@mcp.tool(annotations={_tool_annotations(ep)})")
        lines.append(f"def {func_name}({sig_params}):")
        lines.append(f'    """{description}"""')
        if path_params:
            lines.append(f'    url = BASE_URL + f"{url_path}"')
        else:
            lines.append(f'    url = BASE_URL + "{url_path}"')

        if query_params:
            q = ", ".join(f'"{orig}": {ident}' for orig, ident, _ in query_params)
            lines.append(f"    params = {{{q}}}")
            lines.append("    params = {k: v for k, v in params.items() if v is not None}")
        else:
            lines.append("    params = {}")

        if header_params:
            h = ", ".join(f'"{orig}": {ident}' for orig, ident, _ in header_params)
            lines.append(f"    headers = {{{h}}}")
            lines.append("    headers = {k: v for k, v in headers.items() if v is not None}")
        else:
            lines.append("    headers = {}")

        if body_fields:
            b = ", ".join(f'"{orig}": {ident}' for orig, ident, _ in body_fields)
            lines.append(f"    body = {{{b}}}")
            lines.append("    body = {k: v for k, v in body.items() if v is not None}")
        else:
            lines.append("    body = None")

        method = ep.method.lower()
        if method == "get":
            lines.append("    resp = httpx.get(url, params=params, headers=headers)")
        else:
            lines.append(
                f"    resp = httpx.{method}(url, params=params, headers=headers, json=body)"
            )
        lines.append("    resp.raise_for_status()")
        lines.append("    return resp.json()")
        lines.append("")

    lines.append('if __name__ == "__main__":')
    lines.append("    mcp.run()")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
