"""
Generates a runnable FastMCP server scaffold from the endpoints that
passed the AI-readiness audit. Each OpenAPI operation becomes an MCP
tool with a model-facing description (distinct from the raw API docs).
"""

import re


def _to_snake_case(path: str, method: str) -> str:
    name = re.sub(r"[{}]", "", path)
    name = re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower()
    return f"{method.lower()}_{name}"


def _to_python_identifier(name: str) -> str:
    """Sanitize an OpenAPI parameter name (e.g. 'Idempotency-Key') into a valid Python identifier."""
    ident = re.sub(r"[^a-zA-Z0-9_]", "_", name).lower()
    if ident and ident[0].isdigit():
        ident = f"_{ident}"
    return ident or "param"


def _model_facing_description(ep) -> str:
    """
    Rewrites the raw OpenAPI description into something aimed at a model's
    tool-selection decision: what it's for, and when to use it vs. not.
    """
    base = ep.description.strip() or ep.summary.strip() or f"{ep.method.upper()} {ep.path}"
    write_methods = {"post", "put", "patch", "delete"}
    if ep.method.lower() in write_methods:
        note = " NOTE: this endpoint has side effects — it changes data, it is not read-only."
    else:
        note = " This is a read-only lookup — safe to call speculatively."
    return base + note


def generate_mcp_scaffold(spec: dict, endpoints: list, out_path: str):
    base_url = ""
    servers = spec.get("servers", [])
    if servers:
        base_url = servers[0].get("url", "")

    lines = []
    lines.append('"""')
    lines.append("Auto-generated MCP server scaffold.")
    lines.append("Generated by api-readiness-auditor from an OpenAPI spec.")
    lines.append("Review every tool description before shipping — these are a first draft,")
    lines.append("written to be model-facing rather than copied straight from API docs.")
    lines.append('"""')
    lines.append("")
    lines.append("import httpx")
    lines.append("from mcp.server.fastmcp import FastMCP")
    lines.append("")
    lines.append(f'BASE_URL = "{base_url}"')
    lines.append("")
    lines.append('mcp = FastMCP("generated-api-server")')
    lines.append("")

    for ep in endpoints:
        func_name = _to_snake_case(ep.path, ep.method)
        description = _model_facing_description(ep)
        params = [p for p in ep.parameters if isinstance(p, dict) and p.get("name")]

        path_params, query_params, header_params = [], [], []
        for p in params:
            location = p.get("in", "query")
            entry = (p["name"], _to_python_identifier(p["name"]))
            if location == "path":
                path_params.append(entry)
            elif location == "header":
                header_params.append(entry)
            else:
                query_params.append(entry)

        all_params = path_params + query_params + header_params
        sig_params = ", ".join(f"{ident}: str = None" for _, ident in all_params)

        url_path = ep.path
        for original, ident in path_params:
            url_path = url_path.replace("{" + original + "}", "{" + ident + "}")

        lines.append("@mcp.tool()")
        lines.append(f"def {func_name}({sig_params}):")
        lines.append(f'    """{description}"""')
        if path_params:
            lines.append(f'    url = BASE_URL + f"{url_path}"')
        else:
            lines.append(f'    url = BASE_URL + "{url_path}"')

        if query_params:
            q_entries = ", ".join(f'"{orig}": {ident}' for orig, ident in query_params)
            lines.append(f"    params = {{{q_entries}}}")
            lines.append("    params = {k: v for k, v in params.items() if v is not None}")
        else:
            lines.append("    params = {}")

        if header_params:
            h_entries = ", ".join(f'"{orig}": {ident}' for orig, ident in header_params)
            lines.append(f"    headers = {{{h_entries}}}")
            lines.append("    headers = {k: v for k, v in headers.items() if v is not None}")
        else:
            lines.append("    headers = {}")

        method = ep.method.lower()
        if method == "get":
            lines.append("    resp = httpx.get(url, params=params, headers=headers)")
        else:
            lines.append(f"    resp = httpx.{method}(url, params=params, headers=headers, json={{}})")
        lines.append("    resp.raise_for_status()")
        lines.append("    return resp.json()")
        lines.append("")

    lines.append('if __name__ == "__main__":')
    lines.append("    mcp.run()")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
